package me.mtk.torrey;

import me.mtk.torrey.ir.IRProgram;
import me.mtk.torrey.targets.TargetProgram;

public abstract class TorreyBackend extends TorreyCompiler
{
    /**
     * Generates the target program.
     * 
     * @return TargetProgram The program generated by 
     * this compiler backend.
     * 
     * @param irProgram The IRProgram from which target 
     * code should be generated.
     */
    public abstract TargetProgram generate(IRProgram irProgram);
    
    /**
     * Assembles the target program into a native 
     * executable specific to the target's architecture.
     * 
     * @param program The program to be assembled.
     */
    public abstract void assemble(TargetProgram program);
}