branches:
  - 'issues-34-ci-pipeline'
tagFormat: '${version}'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - prepareRelease: './prepare-semantic-release.sh ${nextRelease.version}'
dryRun: true