name: Continuous Integration

on: [push]

jobs:

  # compile:
  #   name: Compile
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get source code
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '11'
  #         distribution: 'adopt'
  
  #     - name: Compile with Maven
  #       run: mvn --update-snapshots compile

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: artifact-compile
  #         path: |
  #           ./target
  #           ./pom.xml
  #           ./dependency-reduced-pom.xml
  #         if-no-files-found: error
  #         retention-days: 3

  # test:
  #   name: Test
  #   needs: compile
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get source code
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '11'
  #         distribution: 'adopt'

  #     - name: Test with Maven
  #       run: mvn --update-snapshots test

  # build_runtime:
  #   name: Build Runtime
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get source code
  #       uses: actions/checkout@v2
      
  #     - name: Build runtime object file
  #       run: gcc -c ./src/runtime/runtime.c -o runtime.o

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: artifact-build-runtime
  #         path: ./runtime.o
  #         if-no-files-found: error
  #         retention-days: 3
    
    release:
      name: Release
      # needs: build_runtime
      runs-on: ubuntu-latest
      # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      steps:
        - name: Get source code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'

        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'

        - name: Install the semantic-release/exec plugin
          run: npm install @semantic-release/exec -D

        - name: Install the semantic-release/github plugin
          run: npm install @semantic-release/github -D

        - name: Install the semantic-release/git plugin
          run: npm install @semantic-release/git -D

        - name: Generate a new release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npx semantic-release@18
